name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm install -g yarn@1.22
      - run: yarn
      - run: yarn build
        env:
          NODE_OPTIONS: --openssl-legacy-provider
      - name: deploy main
        if: github.ref == 'refs/heads/main'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          yarn global add firebase-tools
          firebase deploy --token "$FIREBASE_TOKEN" --force
